<?php

namespace AppBundle\Repository;

/**
 * BajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BajaRepository extends \Doctrine\ORM\EntityRepository
{
}
