<?php

namespace AppBundle\Repository;

/**
 * estadoAdicionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estadoAdicionalRepository extends \Doctrine\ORM\EntityRepository
{
}
