<?php

namespace AppBundle\Repository;

/**
 * HistorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialRepository extends \Doctrine\ORM\EntityRepository
{
}
