<?php

namespace AppBundle\Repository;

/**
 * ImporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImporteRepository extends \Doctrine\ORM\EntityRepository
{
}
