<?php

namespace AppBundle\Repository;

/**
 * MonedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonedaRepository extends \Doctrine\ORM\EntityRepository
{
}
