<?php

namespace AppBundle\Repository;

/**
 * rol_permisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rol_permisoRepository extends \Doctrine\ORM\EntityRepository
{
}
