<?php

namespace AppBundle\Repository;

/**
 * TransferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
