<?php

namespace AppBundle\Repository;

/**
 * CondicionArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicionArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
