<?php

namespace AppBundle\Repository;

/**
 * EstadoArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
