<?php

namespace AppBundle\Repository;

/**
 * TipoArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
