<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJlje0ak\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJlje0ak/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJlje0ak.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJlje0ak\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJlje0ak\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jlje0ak',
    'container.build_id' => '011dd766',
    'container.build_time' => 1540585565,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJlje0ak');
