<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9tnew7x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9tnew7x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9tnew7x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9tnew7x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9tnew7x\appDevDebugProjectContainer(array(
    'container.build_hash' => '9tnew7x',
    'container.build_id' => '3a2fe444',
    'container.build_time' => 1540672054,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9tnew7x');
