<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLiz4qqz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLiz4qqz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLiz4qqz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLiz4qqz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLiz4qqz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Liz4qqz',
    'container.build_id' => '366e95c6',
    'container.build_time' => 1540924337,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLiz4qqz');
